# Generated by Django 6.0.3 on 2026-03-18 06:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Dam olish kuni')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dam olish kuni',
                'verbose_name_plural': 'Dam olish kunlari',
            },
        ),
        migrations.CreateModel(
            name='LaminationFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Metr narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laminatsiya plyonkasi',
                'verbose_name_plural': 'Laminatsiya plyonkalari',
            },
        ),
        migrations.CreateModel(
            name='ProtectiveFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Metr narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bron plyonka',
                'verbose_name_plural': 'Bron plyonkalar',
            },
        ),
        migrations.CreateModel(
            name='SonsaZashita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('door_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Eshik narxi')),
                ('windshield_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Lobovoy narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sonsa Zashita',
                'verbose_name_plural': 'Sonsa Zashitalar',
            },
        ),
        migrations.CreateModel(
            name='Tonirovka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('door_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Eshik narxi')),
                ('windshield_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Lobovoy narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tonirovka',
                'verbose_name_plural': 'Tonirovkalar',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('salary_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Oylik foizi (%)')),
                ('late_fine', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="10 min kechiksa jarima (so'm)")),
                ('overtime_bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="1 soat qo'shimcha ishlasa bonus (so'm)")),
                ('monday_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Dushanba boshlanish')),
                ('monday_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Dushanba tugash')),
                ('tuesday_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Seshanba boshlanish')),
                ('tuesday_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Seshanba tugash')),
                ('wednesday_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Chorshanba boshlanish')),
                ('wednesday_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Chorshanba tugash')),
                ('thursday_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Payshanba boshlanish')),
                ('thursday_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Payshanba tugash')),
                ('friday_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Juma boshlanish')),
                ('friday_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Juma tugash')),
                ('saturday_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Shanba boshlanish')),
                ('saturday_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Shanba tugash')),
                ('sunday_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Yakshanba boshlanish')),
                ('sunday_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Yakshanba tugash')),
                ('current_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Joriy oylik')),
                ('total_fines', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami jarimalar')),
                ('total_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami bonuslar')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Jami to'langan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
            },
        ),
        migrations.CreateModel(
            name='WorkDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('tonirovka', 'Tonirovka'), ('sonsa', 'Sonsa Zashita'), ('laminatsiya', 'Laminatsiya'), ('bron', 'Bron')], max_length=20, verbose_name='Ish turi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('rear_door_count', models.IntegerField(default=0, verbose_name='Orqa eshik soni')),
                ('front_door_count', models.IntegerField(default=0, verbose_name='Oldi eshik soni')),
                ('rear_windshield_count', models.IntegerField(default=0, verbose_name='Orqa lobovoy soni')),
                ('front_windshield_count', models.IntegerField(default=0, verbose_name='Oldi lobovoy soni')),
                ('is_detailed', models.BooleanField(default=True, verbose_name='Yechilgan detallar')),
                ('meters_used', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ketgan metr')),
                ('car_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mashina nomi')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umumiy narx')),
                ('worker_share', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ishchi ulushi')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlanganmi?')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lamination_film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.laminationfilm')),
                ('protective_film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.protectivefilm')),
                ('sonsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sonsazashita')),
                ('tonirovka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tonirovka')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_done', to='main.worker')),
            ],
            options={
                'verbose_name': 'Bajarilgan ish',
                'verbose_name_plural': 'Bajarilgan ishlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="To'lov miqdori")),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.worker')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bonus miqdori')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Sabab')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langanmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='main.worker')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuslar',
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Kelgan vaqti')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Ketgan vaqti')),
                ('check_in_lat', models.FloatField(blank=True, null=True, verbose_name='Kelgan location lat')),
                ('check_in_lng', models.FloatField(blank=True, null=True, verbose_name='Kelgan location lng')),
                ('check_out_lat', models.FloatField(blank=True, null=True, verbose_name='Ketgan location lat')),
                ('check_out_lng', models.FloatField(blank=True, null=True, verbose_name='Ketgan location lng')),
                ('is_late', models.BooleanField(default=False, verbose_name='Kechikkanmi?')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jarima')),
                ('overtime_minutes', models.IntegerField(default=0, verbose_name="Qo'shimcha ishlagan daqiqalar")),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='main.worker')),
            ],
            options={
                'verbose_name': 'Ish seansi',
                'verbose_name_plural': 'Ish seanslari',
                'ordering': ['-check_in'],
            },
        ),
    ]
