# Generated by Django 6.0.3 on 2026-03-18 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='workdone',
            options={'verbose_name': 'Bajarilgan ish', 'verbose_name_plural': 'Bajarilgan ishlar'},
        ),
        migrations.AlterModelOptions(
            name='worksession',
            options={'verbose_name': 'Ish seansi', 'verbose_name_plural': 'Ish seanslari'},
        ),
        migrations.RemoveField(
            model_name='worker',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laminationfilm',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laminationfilm',
            name='price_per_meter',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='protectivefilm',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='protectivefilm',
            name='price_per_meter',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sonsazashita',
            name='door_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sonsazashita',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sonsazashita',
            name='windshield_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tonirovka',
            name='door_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tonirovka',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tonirovka',
            name='windshield_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='car_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='front_door_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='front_windshield_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='is_detailed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='meters_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='rear_door_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='rear_windshield_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='work_type',
            field=models.CharField(choices=[('tonirovka', 'Tonirovka'), ('sonsa', 'Sonsa Zashita'), ('laminatsiya', 'Laminatsiya'), ('bron', 'Bron')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='worker_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='friday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='friday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='monday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='monday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='overtime_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="1 soat qo'shimcha bonus (so'm)"),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Oylik foizi (%)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='total_bonuses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='total_fines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='check_in_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='check_in_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='check_out_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='check_out_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
