# Generated by Django 6.0.3 on 2026-03-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_payment_options_alter_workdone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='workdone',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Bajarilgan ish', 'verbose_name_plural': 'Bajarilgan ishlar'},
        ),
        migrations.AlterModelOptions(
            name='worksession',
            options={'ordering': ['-check_in'], 'verbose_name': 'Ish seansi', 'verbose_name_plural': 'Ish seanslari'},
        ),
        migrations.RemoveField(
            model_name='sonsazashita',
            name='door_price',
        ),
        migrations.RemoveField(
            model_name='sonsazashita',
            name='windshield_price',
        ),
        migrations.RemoveField(
            model_name='tonirovka',
            name='door_price',
        ),
        migrations.RemoveField(
            model_name='tonirovka',
            name='windshield_price',
        ),
        migrations.AddField(
            model_name='workdone',
            name='bumper_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workdone',
            name='hood_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workdone',
            name='other_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workdone',
            name='other_part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workdone',
            name='roof_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workdone',
            name='selected_parts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workdone',
            name='trunk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
