# Generated by Django 6.0.3 on 2026-03-19 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_payment_options_alter_workdone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_working_friday',
            field=models.BooleanField(default=True, verbose_name='Juma ish kuni?'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_working_monday',
            field=models.BooleanField(default=True, verbose_name='Dushanba ish kuni?'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_working_saturday',
            field=models.BooleanField(default=True, verbose_name='Shanba ish kuni?'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_working_sunday',
            field=models.BooleanField(default=True, verbose_name='Yakshanba ish kuni?'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_working_thursday',
            field=models.BooleanField(default=True, verbose_name='Payshanba ish kuni?'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_working_tuesday',
            field=models.BooleanField(default=True, verbose_name='Seshanba ish kuni?'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_working_wednesday',
            field=models.BooleanField(default=True, verbose_name='Chorshanba ish kuni?'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='is_holiday_work',
            field=models.BooleanField(default=False, verbose_name='Dam olish kunida ishlaganmi?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='friday_end',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Juma tugash'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='friday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Juma boshlanish'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='monday_end',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Dushanba tugash'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='monday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Dushanba boshlanish'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Shanba tugash'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Shanba boshlanish'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Yakshanba tugash'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Yakshanba boshlanish'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Payshanba tugash'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Payshanba boshlanish'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Seshanba tugash'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Seshanba boshlanish'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Chorshanba tugash'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Chorshanba boshlanish'),
        ),
    ]
