# Generated by Django 6.0.3 on 2026-03-19 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_worker_is_working_friday_worker_is_working_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='is_working_friday',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_working_monday',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_working_saturday',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_working_sunday',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_working_thursday',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_working_tuesday',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_working_wednesday',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='is_holiday_work',
        ),
        migrations.AddField(
            model_name='worker',
            name='friday_working',
            field=models.BooleanField(default=True, verbose_name='Juma ish kuni'),
        ),
        migrations.AddField(
            model_name='worker',
            name='monday_working',
            field=models.BooleanField(default=True, verbose_name='Dushanba ish kuni'),
        ),
        migrations.AddField(
            model_name='worker',
            name='saturday_working',
            field=models.BooleanField(default=True, verbose_name='Shanba ish kuni'),
        ),
        migrations.AddField(
            model_name='worker',
            name='sunday_working',
            field=models.BooleanField(default=True, verbose_name='Yakshanba ish kuni'),
        ),
        migrations.AddField(
            model_name='worker',
            name='thursday_working',
            field=models.BooleanField(default=True, verbose_name='Payshanba ish kuni'),
        ),
        migrations.AddField(
            model_name='worker',
            name='tuesday_working',
            field=models.BooleanField(default=True, verbose_name='Seshanba ish kuni'),
        ),
        migrations.AddField(
            model_name='worker',
            name='wednesday_working',
            field=models.BooleanField(default=True, verbose_name='Chorshanba ish kuni'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='is_off_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='friday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='friday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='monday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='monday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
