# Generated by Django 6.0.3 on 2026-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_worker_is_working_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='three_hour_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="3 soatdan keyin bonus (so'm)"),
        ),
        migrations.AddField(
            model_name='worksession',
            name='last_bonus_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi bonus tekshiruvi'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='three_hour_bonus_blocks',
            field=models.IntegerField(default=0, verbose_name='3 soatlik bonus bloklari soni'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='three_hour_total_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='3 soatlik jami bonus'),
        ),
        migrations.AlterField(
            model_name='workdone',
            name='car_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mashina nomi'),
        ),
    ]
