# Generated by Django 6.0 on 2026-03-27 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_worker_three_hour_bonus_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mashina nomi')),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Egasining telefoni')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Barcha qismlar bajarilganmi?')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mashina',
                'verbose_name_plural': 'Mashinalar',
            },
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Qism nomi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standart qism')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='main.car', verbose_name='Mashina')),
            ],
            options={
                'verbose_name': 'Mashina qismi',
                'verbose_name_plural': 'Mashina qismlari',
            },
        ),
        migrations.CreateModel(
            name='CarWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('tonirovka', 'Tonirovka'), ('sonsa', 'Sonsa Zashita'), ('laminatsiya', 'Laminatsiya'), ('bron', 'Bron')], max_length=20, verbose_name='Ish turi')),
                ('work_date', models.DateField(blank=True, null=True, verbose_name='Ish sanasi')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umumiy narx')),
                ('worker_share', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ishchi ulushi')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='main.car', verbose_name='Mashina')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_works', to='main.worker', verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Mashina ishi',
                'verbose_name_plural': 'Mashina ishlari',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarWorkPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='Soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_parts', to='main.carwork', verbose_name='Ish')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carpart', verbose_name='Qism')),
            ],
            options={
                'verbose_name': 'Bajarilgan qism',
                'verbose_name_plural': 'Bajarilgan qismlar',
            },
        ),
    ]
