# Generated by Django 6.0.3 on 2026-03-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_car_carpart_carwork_carworkpart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwork',
            options={},
        ),
        migrations.AlterField(
            model_name='carwork',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='main.car'),
        ),
        migrations.AlterField(
            model_name='carwork',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carwork',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='carwork',
            name='work_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carwork',
            name='work_type',
            field=models.CharField(choices=[('other', 'Boshqa')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='carwork',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_works', to='main.worker'),
        ),
        migrations.AlterField(
            model_name='carwork',
            name='worker_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
