# Generated by Django 6.0.3 on 2026-03-27 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_carwork_options_alter_carwork_car_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="10 min kechiksa jarima (so'm)"),
        ),
        migrations.AlterField(
            model_name='worker',
            name='overtime_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="1 soat qo'shimcha bonus (so'm)"),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Oylik foizi (%)'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
