# Generated by Django 6.0.3 on 2026-03-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_worker_late_fine_alter_worker_overtime_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=255, verbose_name='Yuboruvchi ismi')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin yuborganmi?')),
                ('message_type', models.CharField(choices=[('text', 'Matn'), ('image', 'Rasm'), ('video', 'Video')], default='text', max_length=10)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/images/', verbose_name='Rasm')),
                ('video', models.FileField(blank=True, null=True, upload_to='messages/videos/', verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.worker')),
            ],
            options={
                'verbose_name': 'Guruh xabari',
                'verbose_name_plural': 'Guruh xabarlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
