# Generated by Django 6.0 on 2026-04-03 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_groupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Oy')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('punctuality_score', models.FloatField(default=0, verbose_name='Vaqtida kelish bali (40%)')),
                ('overtime_score', models.FloatField(default=0, verbose_name="Qo'shimcha ish bali (30%)")),
                ('attendance_score', models.FloatField(default=0, verbose_name='Kelgan kunlar bali (30%)')),
                ('total_score', models.FloatField(default=0, verbose_name='Umumiy bal')),
                ('rank', models.IntegerField(default=0, verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='main.worker')),
            ],
            options={
                'ordering': ['-total_score', 'rank'],
                'unique_together': {('worker', 'month', 'year')},
            },
        ),
    ]
