# Generated by Django 6.0.3 on 2026-04-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_workerdiscipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='total_discipline_score',
            field=models.FloatField(default=0, verbose_name='Jami intizom bali'),
        ),
        migrations.CreateModel(
            name='DailyDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('attendance_score', models.FloatField(default=0, verbose_name='Kelganlik bali (maks 8)')),
                ('punctuality_score', models.FloatField(default=0, verbose_name='Vaqtida kelish bali (maks 10)')),
                ('overtime_score', models.FloatField(default=0, verbose_name="Qo'shimcha ish bali (maks 8)")),
                ('total_score', models.FloatField(default=0, verbose_name='Kunlik umumiy bal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_disciplines', to='main.worker')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
